import type { SurveyForm } from "./survey";

export const DEFAULT_FORM: SurveyForm = {
  id: "farm-logic-test",
  title: "Are You Smarter Than a 5th Grader? \u2013 Farm Logic Test \ud83c\udf31",
  subtitle: "90% of engineers fail this simple farm logic test.",
  published: true,
  collectEmails: true,
  updatedAt: "2026-07-27T00:00:00.000Z",
  sections: [
    {
      id: "start",
      title: "Start",
      heading: "Are You Smarter Than a 5th Grader? \u2013 Farm Logic Test \ud83c\udf31",
      subheading: "Pass all 3 levels to prove your common sense.",
      icon: "sprout",
      questions: [
        {
          id: "campus",
          type: "select",
          label: "Campus",
          placeholder: "Select campus",
          required: true,
          options: [
            "School of Commerce",
            "School of Engineering and Technology",
            "School of Aerospace Engineering",
            "School of Computer Science and Engineering",
            "School of Sciences",
            "School of Computer Science and IT",
            "School of Allied Healthcare and Sciences",
            "School of Design, Media and Creative Arts",
            "School of Aviation and Aerospace Management",
            "School of Sports Education and Research",
            "School of Law",
            "CMS Business School - Lalbagh",
            "CMS Business School - Seshadri",
          ],
        },
        {
          id: "ug_pg",
          type: "choice",
          label: "UG/PG",
          required: true,
          options: ["UG", "PG"],
        },
      ],
    },
    {
      id: "details",
      title: "Details",
      heading: "Candidate Details",
      subheading: "This information is only used to share your result and feedback.",
      icon: "person",
      questions: [
        { id: "full_name", type: "text", label: "Full Name", placeholder: "Your full name", required: true },
        { id: "email", type: "email", label: "Email ID", placeholder: "you@example.com", required: true },
        { id: "phone", type: "phone", label: "Phone Number", placeholder: "+91", required: true },
        {
          id: "location",
          type: "select",
          label: "Location",
          placeholder: "Select location",
          required: true,
          options: ["Bangalore", "Kochi"],
        },
        {
          id: "department",
          type: "select",
          label: "Department",
          placeholder: "Select department",
          required: true,
          options: [
            "Department of Humanities & Social Sciences",
            "Department of Economics",
            "Department of Journalism and Mass Communication",
            "Department of Languages",
            "Department of Law",
            "Department of Performing Arts and Cultural Studies",
            "Department of Computer Science and IT",
            "Department of Allied Healthcare and Sciences",
            "Department of Biotechnology and Genetics",
            "Department of Chemistry and Biochemistry",
            "Department of Data Analytics and Mathematical Science",
            "Department of Forensic Science",
            "Department of Microbiology and Botany",
            "Department of Physics and Electronics",
            "Department of Psychology and Allied Sciences",
            "Department of Animation and Virtual Reality",
            "Department of Commerce",
            "Department of Art and Design",
            "Department of Design",
            "Department of Aerospace Engineering",
            "Department of Computer Science and Engineering",
            "Department of Electrical and Electronics Engineering",
            "Department of Electronics and Communication Engineering",
            "Department of Food Technology",
            "Department of Information Science and Engineering",
            "Department of Civil Engineering",
            "Department of Mechanical Engineering",
            "Department of Management Studies - UG",
            "Area - School of Sports Education and Research",
            "CeRSSE",
            "Department of Management Studies - PG",
            "Department of Art and Design (Interior Design)",
          ],
        },
        { id: "course", type: "text", label: "Course", placeholder: "e.g. B.Tech CSE", required: true },
        { id: "usn", type: "text", label: "USN", placeholder: "University Seat Number", required: true },
        { id: "cv", type: "file", label: "CV", required: false },
      ],
    },
    {
      id: "level1",
      title: "Level 1",
      heading: "Level 1 \u2014 Basic Farm Logic \ud83c\udf3e",
      subheading: "Common sense first. A 5th grader gets these right.",
      icon: "leaf",
      questions: [
        {
          id: "l1_q1",
          type: "choice",
          label: "A plant is turning yellow. What should you do?",
          required: true,
          image: "/survey/1.jpg",
          options: ["Pour more water.", "Check if the soil is too wet."],
          correctOption: "Check if the soil is too wet.",
          points: 1,
        },
        {
          id: "l1_q2",
          type: "choice",
          label: "Market Alert! Tomato prices dropped to \u20b92/kg. What do you do?",
          required: true,
          image: "/survey/2.png",
          options: ["Harvest and sell immediately.", "Wait or make Tomato Puree."],
          correctOption: "Wait or make Tomato Puree.",
          points: 1,
        },
        {
          id: "l1_q3",
          type: "choice",
          label: "It is noon and 35\u00b0C outside. When should you water crops?",
          required: true,
          image: "/survey/3.png",
          options: ["Turn on the sprinklers now.", "Wait until evening."],
          correctOption: "Wait until evening.",
          points: 1,
        },
      ],
    },
    {
      id: "level2",
      title: "Level 2",
      heading: "Level 2 \u2014 Jugaad Workshop",
      subheading: "Fix the problem using everyday items.",
      icon: "tractor",
      questions: [
        {
          id: "l2_q1",
          type: "choice",
          label: "The river water is muddy and pipes will get clogged. Which combination makes a basic filter?",
          required: true,
          options: ["Bucket + Sand + Stones + Cloth", "Bottle + Rope", "Plastic sheet only"],
          correctOption: "Bucket + Sand + Stones + Cloth",
          points: 1,
        },
        {
          id: "l2_q2",
          type: "choice",
          label: "An irrigation pipe is leaking and the shop is closed. What is the temporary fix?",
          required: true,
          options: ["Rubber strip + Wire / Clamp", "Sand only", "Plastic bottle"],
          correctOption: "Rubber strip + Wire / Clamp",
          points: 1,
        },
        {
          id: "l2_q3",
          type: "choice",
          label: "Bugs are destroying your leaves and no chemicals are available. Choose the best trap.",
          required: true,
          options: ["Yellow plastic sheet + oil/grease", "Water spray", "Rope fence"],
          correctOption: "Yellow plastic sheet + oil/grease",
          points: 1,
        },
      ],
    },
    {
      id: "level3",
      title: "Level 3",
      heading: "Level 3 \u2014 Udyaan Tycoon",
      subheading: "You start with \u20b910,000. Make smart decisions.",
      icon: "chart",
      questions: [
        {
          id: "l3_q1",
          type: "choice",
          label: "Which seeds will you buy?",
          required: true,
          options: ["Cheap seeds (\u20b9100)", "Certified high-yield seeds (\u20b9500)"],
          correctOption: "Certified high-yield seeds (\u20b9500)",
          points: 1,
        },
        {
          id: "l3_q2",
          type: "choice",
          label: "Heavy rains predicted! What do you do?",
          required: true,
          options: ["Spend \u20b92000 on drainage", "Save money and sow seeds for the next hours"],
          correctOption: "Spend \u20b92000 on drainage",
          points: 1,
        },
        {
          id: "l3_q3",
          type: "choice",
          label: "How will you sell your produce?",
          required: true,
          options: [
            "Sell to middleman (low price, instant income, no risk)",
            "Sell directly to apartments (high effort, high profit)",
          ],
        },
      ],
    },
    {
      id: "reflect",
      title: "Reflect",
      heading: "Reflection & Intent Questions",
      subheading: "A few honest, open questions \u2014 there's no right answer here.",
      icon: "spiral",
      questions: [
        {
          id: "reflect_interest",
          type: "longtext",
          label:
            "What's pulling you toward agriculture specifically, and what are you actually willing to risk to build something in it on your own?",
          placeholder: "Share the specific connection, opportunity, or curiosity pulling you in, and the commitment you are prepared to make.",
          required: true,
        },
        {
          id: "reflect_decision",
          type: "longtext",
          label: "Describe a time you had to make a call on your own, with no one to check it against. What happened?",
          placeholder: "Describe the situation, the decision you made, what happened, and what you learned.",
          required: true,
        },
        {
          id: "reflect_improve",
          type: "longtext",
          label:
            "Tell us about a setback or rejection in something you were building or pursuing. How did you respond, and did you continue?",
          placeholder: "Tell us what changed after the setback and why you continued, paused, or stopped.",
          required: true,
        },
        {
          id: "reflect_resource",
          type: "longtext",
          label: "How would you find out if an agri idea is actually worth building, before you spend months on it?",
          placeholder: "Explain the first steps you would take to test the problem and the evidence you would look for.",
          required: true,
        },
        {
          id: "reflect_idea",
          type: "longtext",
          label:
            "Picture yourself six months into building this alone. What have you actually built, and what would convince you it's worth continuing?",
          placeholder: "Describe the concrete result you want after six months and the signal that would make you continue.",
          required: true,
        },
      ],
    },
    {
      id: "review",
      title: "Review",
      heading: "Review & Submit \ud83c\udf8a",
      subheading: "Check your answers before you submit. You can go back to any section.",
      icon: "confetti",
      questions: [],
    },
  ],
};

/** Keep the onboarding reflection prompts canonical without overwriting other admin form edits. */
export function withCanonicalReflect(form: SurveyForm): SurveyForm {
  const canonical = DEFAULT_FORM.sections.find((section) => section.id === "reflect");
  if (!canonical) return form;

  return {
    ...form,
    sections: form.sections.map((section) =>
      section.id === "reflect"
        ? {
            ...section,
            heading: canonical.heading,
            subheading: canonical.subheading,
            questions: canonical.questions,
          }
        : section,
    ),
  };
}
